In [1]:
from matplotlib import pyplot as plt
import numpy as np
%matplotlib widget

In [2]:
points_3d = np.array([[ 0.,          0.,          0.        ],
 [-0.03138264, -0.09922726,  0.00946505],
 [-0.07037588,  0.07883613,  0.0089331 ],
 [ 0.10787677,  0.02588217,  0.00836965]])
keypoints_2d = np.array([[603.39123535, 301.11212158],
 [640.75494385, 396.78601074],
 [556.61352539, 291.11450195],
 [697.81604004, 276.12750244]])


In [3]:
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(points_3d[:, 0], points_3d[:, 1], points_3d[:, 2], c=np.linspace(0, 1, 4), cmap='summer')
ax.set_xlim(-0.15, 0.15)
ax.set_ylim(-0.15, 0.15)
ax.set_zlim(-0.15, 0.15)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(-0.15, 0.15)

In [4]:
figure = plt.figure()
plt.scatter(keypoints_2d[:, 0], keypoints_2d[:, 1], c=np.arange(4), cmap='summer')
plt.xlim(0, 1280)
plt.ylim(0, 720)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(0.0, 720.0)

In [5]:
import cv2
K = np.array([[697.87732212 , 0. , 648.08562626],
 [  0., 697.28594061, 371.49958099],
 [  0., 0.,1.        ]]) / 8.0
D = np.array([-1.74610270e-01,  2.75427408e-02,  6.24873971e-05,  9.10956548e-05])

In [21]:
success, rotvec, tvec = cv2.solvePnP(points_3d, keypoints_2d, K, np.zeros(4), flags=cv2.SOLVEPNP_EPNP)
T = np.eye(4)
R, _ = cv2.Rodrigues(rotvec)
T[:3, :3] = R
T[:3, 3] = tvec[:, 0]
success, T

(True,
 array([[ 0.75168222, -0.27787168,  0.5981314 , -0.0314786 ],
        [-0.45333637, -0.87638764,  0.16257562, -0.06893673],
        [ 0.47901981, -0.39335992, -0.78473435,  0.89141784],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]))

In [22]:
predicted_points = (T @ np.concatenate([points_3d, np.ones((4, 1))], axis=1)[:,:, None])[:, :, 0]
predicted_points

array([[-0.0314786 , -0.06893673,  0.89141784,  1.        ],
       [-0.02183458,  0.03379049,  0.90798941,  1.        ],
       [-0.10094206, -0.10467149,  0.81968532,  1.        ],
       [ 0.04742468, -0.1391633 ,  0.92634399,  1.        ]])

In [24]:
fig = plt.figure()
reprojected = (K @ predicted_points[:, :3, None])[:, :, 0]
reprojected = reprojected / reprojected[:, 2:3]
print(reprojected)

plt.scatter(keypoints_2d[:, 0], keypoints_2d[:, 1], c=np.linspace(0, 1, keypoints_2d.shape[0]), cmap='spring')
plt.scatter(reprojected[:, 0], reprojected[:, 1], c=np.linspace(0, 1, reprojected.shape[0]), cmap='spring')
plt.xlim(0, 1280)
plt.ylim(0, 720)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[[623.44151511 317.57581015   1.        ]
 [631.30364683 397.44882302   1.        ]
 [562.14389836 282.4581459    1.        ]
 [683.81383124 266.74733235   1.        ]]


(0.0, 720.0)

In [9]:
(K @ predicted_points[:, :3, None])[:, :, 0]

array([[525.72722885, 262.88184879,   0.83918927],
       [564.64292418, 344.10913791,   0.88081192],
       [450.11823921, 233.91501349,   0.82930932],
       [543.28804458, 205.62918175,   0.78049184]])

In [10]:
predicted_points

array([[-0.02599206, -0.07009551,  0.83918927,  1.        ],
       [-0.0088821 ,  0.02421945,  0.88081192,  1.        ],
       [-0.1251584 , -0.10637394,  0.82930932,  1.        ],
       [ 0.05368064, -0.1209306 ,  0.78049184,  1.        ]])